-- INSERT ROW FOR ET_APPS 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETApps', 
              'ET_APPS', 
              'APP_ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_APP_STRUCTURE 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETAppStructure', 
              'ET_APP_STRUCTURE', 
              'ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_DATA_SOURCES 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETDatasources', 
              'ET_DATA_SOURCES', 
              'ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_FILES 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETFiles', 
              'ET_FILES', 
              'FILE_ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_INTERPRETERS 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETInterpreters', 
              'ET_INTERPRETERS', 
              'ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_TEMPLATE_STRUCTURE 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETTemplateStructure', 
              'ET_TEMPLATE_STRUCTURE', 
              'ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_TEMPLATES 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETTemplates', 
              'ET_TEMPLATES', 
              'TEMPLATE_ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_USERS 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETUsers', 
              'ET_USERS', 
              'USER_ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 

-- INSERT ROW FOR ET_WIDGETS 
INSERT INTO `everything_db`.`et_data_sources` 
            (`name`, 
             `table_name`, 
             `pk_id`, 
             `seq_name`, 
             `schema_name`, 
             `ext1`, 
             `ext2`, 
             `n_ext1`, 
             `n_ext2`, 
             `d_ext1`, 
             `d_ext2`, 
             `created_by`, 
             `creation_date`, 
             `last_updated_by`, 
             `last_update_date`) 
VALUES      ( 'ETWidgets', 
              'ET_WIDGETS', 
              'ID', 
              NULL, 
              'EVERYTING_DB', 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              NULL, 
              1, 
              Sysdate(), 
              1, 
              Sysdate()); 