INSERT INTO `et_users` 
            (`user_id`, 
             `user_name`, 
             `display_name`, 
             `email_address`, 
             `encrypt_password`, 
             `avatar_url`, 
             `creation_date`, 
             `last_login_date`, 
             `last_login_ip`, 
             `ext1`, 
             `ext2`, 
             `n_ext3`, 
             `n_ext4`, 
             `d_ext5`, 
             `d_ext6`) 
VALUES      (1, 
             'Venkatesh', 
             'Venkatesh', 
             'venki.jakka@gmail.com', 
             '$2a$12$HghLO4yAoMHeZHVpgM7I6e73uLU0tI51V9Ev88K0EpNoH57Y5QWO.', 
             NULL, 
             '2015-08-05 18:01:08', 
             '2015-08-05 18:01:08', 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             '0000-00-00 00:00:00', 
             '0000-00-00 00:00:00'); 