USE EVERYTING_DB;

DROP TABLE IF EXISTS ET_WIDGETS; 
CREATE TABLE ET_WIDGETS(
ID INT AUTO_INCREMENT PRIMARY KEY,
WIDGET_ID VARCHAR(150) NOT NULL UNIQUE,
WIDGET_NAME VARCHAR(100) NOT NULL,
WIDGET_GROUP VARCHAR(100),
SYNTAX TEXT NOT NULL,
THUMBNAIL TEXT,
TAGS VARCHAR(2000),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_widgets`
(`ID`,
`WIDGET_ID`,
`WIDGET_NAME`,
`WIDGET_GROUP`,
`SYNTAX`,
`THUMBNAIL`,
`TAGS`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{ID: }>,
<{WIDGET_ID: }>,
<{WIDGET_NAME: }>,
<{WIDGET_GROUP: }>,
<{SYNTAX: }>,
<{THUMBNAIL: }>,
<{TAGS: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: CURRENT_TIMESTAMP}>,
<{D_EXT6: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_USERS; 
CREATE TABLE ET_USERS(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(200) UNIQUE NOT NULL,
DISPLAY_NAME VARCHAR(200),
EMAIL_ADDRESS VARCHAR(250) UNIQUE NOT NULL,
ENCRYPT_PASSWORD VARCHAR(1000) NOT NULL,
AVATAR_URL VARCHAR(250),
CREATION_DATE TIMESTAMP,
LAST_LOGIN_DATE TIMESTAMP,
LAST_LOGIN_IP VARCHAR(250),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_users`
(`USER_ID`,
`USER_NAME`,
`DISPLAY_NAME`,
`EMAIL_ADDRESS`,
`ENCRYPT_PASSWORD`,
`AVATAR_URL`,
`CREATION_DATE`,
`LAST_LOGIN_DATE`,
`LAST_LOGIN_IP`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`)
VALUES
(<{USER_ID: }>,
<{USER_NAME: }>,
<{DISPLAY_NAME: }>,
<{EMAIL_ADDRESS: }>,
<{ENCRYPT_PASSWORD: }>,
<{AVATAR_URL: }>,
<{CREATION_DATE: CURRENT_TIMESTAMP}>,
<{LAST_LOGIN_DATE: 0000-00-00 00:00:00}>,
<{LAST_LOGIN_IP: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: 0000-00-00 00:00:00}>,
<{D_EXT6: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_TEMPLATES; 
CREATE TABLE ET_TEMPLATES(
TEMPLATE_ID INT AUTO_INCREMENT PRIMARY KEY,
TEMPLATE_NAME VARCHAR(250) NOT NULL,
THUMBNAIL_URL VARCHAR(250),
THEME VARCHAR(150),
VERSION VARCHAR(50),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_templates`
(`TEMPLATE_ID`,
`TEMPLATE_NAME`,
`THUMBNAIL_URL`,
`THEME`,
`VERSION`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{TEMPLATE_ID: }>,
<{TEMPLATE_NAME: }>,
<{THUMBNAIL_URL: }>,
<{THEME: }>,
<{VERSION: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: CURRENT_TIMESTAMP}>,
<{D_EXT6: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_TEMPLATE_STRUCTURE; 
CREATE TABLE ET_TEMPLATE_STRUCTURE(
ID INT AUTO_INCREMENT PRIMARY KEY,
UID VARCHAR(250) UNIQUE,
TYPE VARCHAR(20) NOT NULL,
TITLE VARCHAR(250) NOT NULL,
PARENT_UID INT NOT NULL, 
TEMPLATE_ID INT NOT NULL,
FILE_CONTENT LONGBLOB,
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP,
UNIQUE KEY ET_TEMPLATE_STRUCTURE_U1 (UID,PARENT_UID)
);

--
INSERT INTO `everything_db`.`et_template_structure`
(`ID`,
`UID`,
`TYPE`,
`TITLE`,
`PARENT_UID`,
`TEMPLATE_ID`,
`FILE_CONTENT`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{ID: }>,
<{UID: }>,
<{TYPE: }>,
<{TITLE: }>,
<{PARENT_UID: }>,
<{TEMPLATE_ID: }>,
<{FILE_CONTENT: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: CURRENT_TIMESTAMP}>,
<{D_EXT6: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_APPS;
CREATE TABLE ET_APPS(
APP_ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(250) NOT NULL,
THEME VARCHAR(100) NOT NULL,
TEMPLATE_ID INT NOT NULL,
ICON VARCHAR(100),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP,
IS_PUBLISHED VARCHAR(1),
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_apps`
(`APP_ID`,
`TITLE`,
`THEME`,
`TEMPLATE_ID`,
`ICON`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`,
`IS_PUBLISHED`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{APP_ID: }>,
<{TITLE: }>,
<{THEME: }>,
<{TEMPLATE_ID: }>,
<{ICON: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: CURRENT_TIMESTAMP}>,
<{D_EXT6: 0000-00-00 00:00:00}>,
<{IS_PUBLISHED: }>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);
--



DROP TABLE IF EXISTS ET_APP_STRUCTURE;
CREATE TABLE ET_APP_STRUCTURE(
ID INT AUTO_INCREMENT PRIMARY KEY,
TYPE VARCHAR(50) NOT NULL,
NAME VARCHAR(250) NOT NULL,
PARENT_ID INT NOT NULL,
APP_ID INT NOT NULL,
FILE_CONTENT LONGBLOB,
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT3 INT,
N_EXT4 INT,
D_EXT5 TIMESTAMP,
D_EXT6 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_app_structure`
(`ID`,
`TYPE`,
`NAME`,
`PARENT_ID`,
`APP_ID`,
`FILE_CONTENT`,
`EXT1`,
`EXT2`,
`N_EXT3`,
`N_EXT4`,
`D_EXT5`,
`D_EXT6`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{ID: }>,
<{TYPE: }>,
<{NAME: }>,
<{PARENT_ID: }>,
<{APP_ID: }>,
<{FILE_CONTENT: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT3: }>,
<{N_EXT4: }>,
<{D_EXT5: CURRENT_TIMESTAMP}>,
<{D_EXT6: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_FILES;
CREATE TABLE ET_FILES(
FILE_ID INT PRIMARY KEY AUTO_INCREMENT,
FILE_NAME VARCHAR(200) NOT NULL,
FILE_TYPE VARCHAR(100),
FILE_SIZE INT,
FILE_PATH VARCHAR(200),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT1 INT,
N_EXT2 INT,
D_EXT1 TIMESTAMP,
D_EXT2 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_files`
(`FILE_ID`,
`FILE_NAME`,
`FILE_TYPE`,
`FILE_SIZE`,
`FILE_PATH`,
`EXT1`,
`EXT2`,
`N_EXT1`,
`N_EXT2`,
`D_EXT1`,
`D_EXT2`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{FILE_ID: }>,
<{FILE_NAME: }>,
<{FILE_TYPE: }>,
<{FILE_SIZE: }>,
<{FILE_PATH: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT1: }>,
<{N_EXT2: }>,
<{D_EXT1: CURRENT_TIMESTAMP}>,
<{D_EXT2: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_INTERPRETERS;
CREATE TABLE ET_INTERPRETERS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200) NOT NULL UNIQUE,
LANG VARCHAR(50),
CONTENT LONGBLOB,
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT1 INT,
N_EXT2 INT,
D_EXT1 TIMESTAMP,
D_EXT2 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_interpreters`
(`ID`,
`NAME`,
`LANG`,
`CONTENT`,
`EXT1`,
`EXT2`,
`N_EXT1`,
`N_EXT2`,
`D_EXT1`,
`D_EXT2`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{ID: }>,
<{NAME: }>,
<{LANG: }>,
<{CONTENT: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT1: }>,
<{N_EXT2: }>,
<{D_EXT1: CURRENT_TIMESTAMP}>,
<{D_EXT2: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--

DROP TABLE IF EXISTS ET_DATA_SOURCES;
CREATE TABLE ET_DATA_SOURCES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200),
TABLE_NAME VARCHAR(200),
PK_ID INT,
SEQ_NAME VARCHAR(50),
SCHEMA_NAME VARCHAR(200),
EXT1 VARCHAR(550),
EXT2 VARCHAR(550),
N_EXT1 INT,
N_EXT2 INT,
D_EXT1 TIMESTAMP,
D_EXT2 TIMESTAMP
CREATED_BY INT,
CREATION_DATE TIMESTAMP,
LAST_UPDATED_BY INT,
LAST_UPDATE_DATE TIMESTAMP
);

--
INSERT INTO `everything_db`.`et_data_sources`
(`ID`,
`NAME`,
`TABLE_NAME`,
`PK_ID`,
`SEQ_NAME`,
`SCHEMA_NAME`,
`EXT1`,
`EXT2`,
`N_EXT1`,
`N_EXT2`,
`D_EXT1`,
`D_EXT2`,
`CREATED_BY`,
`CREATION_DATE`,
`LAST_UPDATED_BY`,
`LAST_UPDATE_DATE`)
VALUES
(<{ID: }>,
<{NAME: }>,
<{TABLE_NAME: }>,
<{PK_ID: }>,
<{SEQ_NAME: }>,
<{SCHEMA_NAME: }>,
<{EXT1: }>,
<{EXT2: }>,
<{N_EXT1: }>,
<{N_EXT2: }>,
<{D_EXT1: CURRENT_TIMESTAMP}>,
<{D_EXT2: 0000-00-00 00:00:00}>,
<{CREATED_BY: }>,
<{CREATION_DATE: 0000-00-00 00:00:00}>,
<{LAST_UPDATED_BY: }>,
<{LAST_UPDATE_DATE: 0000-00-00 00:00:00}>);

--