DELETE FROM ET_DS WHERE ID > 0;
DELETE FROM ET_DS_ATTRS WHERE ID > 0;

-- 1.ET_PAGES
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etPages", "ET_PAGES", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "PAGE_NAME", "VARCHAR(200)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "STATE", "VARCHAR(200)", NULL , "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "CONTROLLER", "VARCHAR(100)", NULL , "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "URL", "VARCHAR(200)", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "ICON", "VARCHAR(100)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "SHOW_IN_MENU", "VARCHAR(1)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "HTML_BLOB_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "JS_BLOB_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "LAZY_LOAD", "LONGBLOB", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_PAGES", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_PAGES", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );


-- 2.ET_INTERPRETERS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etInterpreters","ET_INTERPRETERS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "NAME", "VARCHAR(200)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "LANG", "VARCHAR(50)", NULL , "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "ICON", "VARCHAR(50)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "IS_ACTIVE", "VARCHAR(1)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "CONTENT", "LONGBLOB", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_INTERPRETERS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_INTERPRETERS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );


-- 3.ET_FILES
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etFiles","ET_FILES", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "FILE_NAME", "VARCHAR(200)", "NULL", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "CONTENT_TYPE", "VARCHAR(100)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "FILE_SIZE", "INT", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "FILE_PATH", "VARCHAR(200)", "NULL", "Y", "N", NULL, NULL );        
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_FILES", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_FILES", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );

-- 4.ET_BLOBS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etBlobs","ET_BLOBS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "FILE_NAME", "VARCHAR(200)", "NULL", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "CONTENT_TYPE", "VARCHAR(100)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "CONTENT", "BLOB", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_BLOBS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_BLOBS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
    
    
--  5.ET_APPS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etApps","ET_APPS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "TITLE", "VARCHAR(250)", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "THEME", "VARCHAR(100)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "TEMPLATE_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "ICON", "VARCHAR(100)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APPS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_APPS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );  

-- 6.ET_APP_STRUCTURE
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etAppStructure","ET_APP_STRUCTURE", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "UID", "VARCHAR(250)",NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "NAME", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "IS_FOLDER", "VARCHAR(1)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "PATH", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "PARENT_UID", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "APP_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "FILE_CONTENT", "LONGBLOB", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_APP_STRUCTURE", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_APP_STRUCTURE", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL ); 


-- 7.ET_TEMPLATES
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etTemplates","ET_TEMPLATES", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "TEMPLATE_NAME", "VARCHAR(250)", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "THUMBNAIL_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "THEME", "VARCHAR(150)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "VERSION", "VARCHAR(50)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATES", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_TEMPLATES", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );    
    

-- 8.ET_TEMPLATE_STRUCTURE
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etTemplateStructure","ET_TEMPLATE_STRUCTURE", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "UID", "VARCHAR(250)",NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "IS_FOLDER", "VARCHAR(1)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "NAME", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "PARENT_UID", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "TEMPLATE_ID", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "PATH", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "FILE_CONTENT", "LONGBLOB", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_TEMPLATE_STRUCTURE", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_TEMPLATE_STRUCTURE", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );  

-- 9.ET_WIDGETS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etWidgets","ET_WIDGETS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "WIDGET_ID", "VARCHAR(150)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "WIDGET_NAME", "VARCHAR(100)", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "WIDGET_GROUP", "VARCHAR(100)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "SYNTAX", "TEXT", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "THUMBNAIL", "TEXT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "TAGS", "VARCHAR(2000)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_WIDGETS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_WIDGETS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );   


-- 10.ET_USERS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etUsera","ET_USERS", "USER_ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "USER_ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "USER_NAME", "VARCHAR(200)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "DISPLAY_NAME", "VARCHAR(200)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "EMAIL_ADDRESS", "VARCHAR(250)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "ENCRYPT_PASSWORD", "VARCHAR(1000)", NULL, "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "AVATAR_URL", "VARCHAR(250)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_USERS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_USERS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );



-- 11.ET_DS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etDS","ET_DS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "TABLE_NAME", "VARCHAR(50)", "UNQ", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "TABLE_NAME", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "PK_NAME", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "SEQ_NAME", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "SCHEMA_NAME", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "DB_VENDOR", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_DS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );


-- 12.ET_DS_ATTRS
INSERT INTO ET_DS(ALT_NAME, TABLE_NAME, PK_NAME, SCHEMA_NAME, DB_VENDOR) 
		     VALUES("etDSAttrs","ET_DS_ATTRS", "ID", NULL, "MYSQL");
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "ID", "INT", "PRI", "N", "Y", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "TABLE_NAME", "VARCHAR(50)", "NULL", "N", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "COLUMN_NAME", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "DATA_TYPE", "VARCHAR(50)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "KEY_TYPE", "VARCHAR(20)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "IS_NULL", "VARCHAR(1)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "IS_AI", "VARCHAR(1)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "SEQUENCE", "VARCHAR(100)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "DEFAULT_VALUE", "VARCHAR(500)", "NULL", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "EXT1", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "EXT2", "VARCHAR(550)", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "N_EXT1", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "N_EXT2", "INT", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "D_EXT1", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "D_EXT2", "TIMESTAMP", NULL, "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "CREATED_BY", "INT", "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "CREATION_DATE", "TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		    VALUES("ET_DS_ATTRS", "LAST_UPDATED_BY", "INT",  "WHO", "Y", "N", NULL, NULL );
INSERT INTO ET_DS_ATTRS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, KEY_TYPE, IS_NULL, IS_AI, SEQUENCE, DEFAULT_VALUE)
		VALUES("ET_DS_ATTRS", "LAST_UPDATE_DATE", 	"TIMESTAMP",  "WHO", "Y", "N", NULL, NULL );  

UPDATE ET_DS SET CREATION_DATE = SYSDATE()-1,
LAST_UPDATE_DATE = SYSDATE()-1,CREATED_BY = 1,
LAST_UPDATED_BY = 1 WHERE ID > 0;

UPDATE ET_DS_ATTRS SET CREATION_DATE = SYSDATE()-1,
LAST_UPDATE_DATE = SYSDATE()-1,CREATED_BY = 1,
LAST_UPDATED_BY = 1 WHERE ID > 0;
